version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
    - inception
    build: 
      requirements/mariadb
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart : always
    expose:
    - "3306"
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build: 
      requirements/nginx
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build: 
      requirements/wordpress
    depends_on:
    - mariadb
    restart: on-failure
    expose: 
    - "9000"
networks :
  inception:

volumes:
  mariadb:
    driver_opts:
      o: bind
      type: "nfs"
      device: "/home/amontant/data/mariadb"
  wordpress:
    driver_opts:
      o: bind
      type: "nfs"
      device: "/home/amontant/data/wordpress"